services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recipe123
      POSTGRES_DB: recipe_app
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8432:5432"
  backend:
    image: bazenmek/recipe-app:backend-latest
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: recipe123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recipe_app
      JWT_SECRET: your_secret_key
      SPOONACULAR_API_KEY: f973aa70f8104d0babff704c934084db
    ports:
      - "8001:5000"
  frontend:
    image: bazenmek/recipe-app:frontend-latest
    environment:
      REACT_APP_API_URL: http://localhost:8001/api
    ports:
      - "8000:3000"
    depends_on:
      - backend
volumes:
  postgres_data:
